<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Khajas-MacBook-Pro.local" failures="2" tests="2" name="Command line test" time="200.729" errors="0" timestamp="24 Apr 2020 05:42:58 GMT">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="185.661">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: Warning message displayed expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Warning message displayed expected [true] but found [false]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at applitools.testrunner.TestRunner.testRunner(TestRunner.java:42)
at applitools.testrunner.TestRunner.executeTest(TestRunner.java:29)
Caused by: java.lang.AssertionError: Warning message displayed expected [true] but found [false]
at applitools.utils.AssertUtils.assertTrue(AssertUtils.java:26)
at applitools.stepdefinitions.TraditionalTestStepDefinitions.verify_no_credentials_warning_message(TraditionalTestStepDefinitions.java:57)
at ✽.Then Verify No Credentials Warning message(TraditionalTest.feature:11)
... Removed 60 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="14.246">
    <failure type="cucumber.runtime.CucumberException" message="com.applitools.eyes.EyesException: eyes.openBase() failed">
      <![CDATA[cucumber.runtime.CucumberException: com.applitools.eyes.EyesException: eyes.openBase() failed
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at applitools.testrunner.TestRunner.testRunner(TestRunner.java:42)
at applitools.testrunner.TestRunner.executeTest(TestRunner.java:29)
Caused by: com.applitools.eyes.EyesException: eyes.openBase() failed
at com.applitools.eyes.EyesBase.openBase(EyesBase.java:1034)
at com.applitools.eyes.selenium.SeleniumEyes.open(SeleniumEyes.java:279)
at com.applitools.eyes.selenium.SeleniumEyes.open(SeleniumEyes.java:242)
at com.applitools.eyes.selenium.Eyes.open(Eyes.java:1164)
at applitools.stepdefinitions.VisualAITestStepDefinitions.launch_the_demo_app_version2(VisualAITestStepDefinitions.java:29)
at ✽.Given Launch the Demo APP version2(VisualAITest.feature:9)
... Removed 57 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Command line test -->
